import type { Lang } from './types'

/** Interface copy, in the reader's language. One place, so it stays consistent. */
export const COPY = {
  appName: '双语阅读器',
  appSubtitle: 'Bilingual Reader',
  shelfTitle: '章节目录',
  shelfReading: '正在读取本地文件夹 …',
  shelfCount: (count: number) => `${count} 章`,
  langLabel: (lang: Lang) => LANG_LABEL[lang],
  langSwitchLabel: '本栏显示内容',
  missingSource: (lang: Lang) => MISSING_SOURCE[lang],
  missingSuggestion: (labels: string[]) =>
    labels.length ? `切到 ${labels.join(' / ')}。` : '这一章的文件夹里没有可用文件。',
  noChapterTitle: '还没有选择章节。',
  noChapterSub: '从左侧「目录」里选一章；书架还是空的，就点目录底部的「导入文件夹」。',
  unreadableTitle: '这一章暂时读不出来。',
  unreadableSub: (title: string) =>
    `「${title}」的文件夹现在打不开：在目录里点它一次重新授权，或用行尾按钮重新选择、移除这一章。`,
  loading: '载入中 …',
  loadFailedTitle: '这一章读不出来。',
  loadFailedSub: (path: string, detail: string) => `${path} → ${detail}`,
  outlineTitle: '大纲',
  outlineToggleTitle: '显示本栏的大纲',
  adhdTitle: 'ADHD',
  adhdToggleTitle: 'ADHD 速览：本章的压缩版',
  adhdMissing: '本章没有 ADHD 速览。',
  openPdf: '原件',
  openPdfTitle: '在新标签页打开原件',
  navToggle: '目录',
  splitRightTitle: '向右分栏',
  splitDownTitle: '向下分栏',
  closePaneTitle: '关闭这一栏',
  paneLimitTitle: (max: number) => `最多 ${max} 栏`,
  missingMark: (labels: string[]) => `缺${labels.join('·')}`,
  missingMarkTitle: (labels: string[]) => `本章文件夹里没有 ${labels.join('、')}`,
  minutes: (value: number) => `${value} min`,
  minutesTitle: (value: number) => `约 ${value} 分钟`,

  /* bookshelf */
  importLabel: '导入文件夹',
  importTitle: '导入一章的文件夹（chromium 才有目录选择器）',
  statusPermission: '需要授权',
  statusMissing: '文件夹不可用',
  statusLoading: '读取中 …',
  statusPermissionTitle: '点一下，让浏览器重新读取这个文件夹',
  statusMissingTitle: '文件夹被移动、删除或改名了：可以重新选择，也可以移除这一章',
  renameChapter: '重命名这一章',
  removeChapter: '移除这一章',
  removeConfirm: (title: string) => `从书架移除「${title}」？磁盘上的文件夹不会被删除。`,
  unsupportedTitle: '这个浏览器不能导入文件夹。',
  unsupportedSub: '导入本地文件夹需要 File System Access API，请换成 Chrome 或 Edge。',

  /* import dialog */
  dialogImportTitle: '导入章节文件夹',
  dialogRenameTitle: '重命名这一章',
  dialogRelinkTitle: '重新选择文件夹',
  dialogFormatTitle: '文件夹格式',
  dialogFormatLines: [
    'zh.md —— 中文章节（可选）',
    'en.md —— English chapter（可选）',
    'adhd.md —— 可选，英文压缩速览',
    '任意一个 *.pdf —— 可选，原件',
    'images/ —— 可选，markdown 里相对路径引用的图片',
  ],
  dialogFormatTip: 'zh.md / en.md / *.pdf 至少要有一个；缺哪个，对应的按钮就不可用。',
  dialogPick: '选择文件夹',
  dialogDrop: '把文件夹拖到这里',
  dialogDropHint: '或者点上面的「选择文件夹」',
  dialogPicked: (name: string) => `已选择：${name}`,
  dialogDetected: (files: string) => `识别到：${files}`,
  dialogNoFiles: '这个文件夹里没有可识别的文件（需要 zh.md / en.md / adhd.md / 任意 pdf）。',
  pickRequired: '请先选择文件夹。',
  dialogDropUnsupported: '这个浏览器拖拽拿不到文件夹，请点「选择文件夹」。',
  numLabel: 'Chapter no',
  numPlaceholder: '如 04',
  nameLabel: 'Chapter name',
  namePlaceholder: '如 Processes',
  numHint: '章节号用于排序，留空则排在最后。',
  nameRequired: '请填 Chapter name。',
  confirmImport: '导入',
  confirmSave: '保存',
  cancel: '取消',
  folderFailed: (detail: string) => `读不了这个文件夹：${detail}`,
} as const

const LANG_LABEL: Record<Lang, string> = { zh: '中文', en: 'English', pdf: '原件' }

const MISSING_SOURCE: Record<Lang, string> = {
  zh: '本章还没有中文版。',
  en: 'This chapter has no English version.',
  pdf: '本章没有附原件 PDF。',
}
